"""Shared template labels and aliases for AI smart rule parsing."""

SUPPORTED_RULE_TYPES = {
    "not_null",
    "unique",
    "regex_check",
    "sequence_order_check",
    "fixed_value_compare",
    "cross_table_mapping",
    "composite_condition_check",
    "dual_composite_compare",
    "multi_composite_pipeline_check",
    "multi_composite_mapping_check",
    "package_items_compare",
    "event_task_reward",
    "event_task_validation",
}
RULE_TYPE_ALIASES = {
    "非空": "not_null",
    "非空校验": "not_null",
    "不能为空": "not_null",
    "必填": "not_null",
    "唯一": "unique",
    "唯一校验": "unique",
    "不能重复": "unique",
    "不可重复": "unique",
    "固定值": "fixed_value_compare",
    "固定值比较": "fixed_value_compare",
    "枚举": "fixed_value_compare",
    "枚举校验": "fixed_value_compare",
    "正则": "regex_check",
    "正则校验": "regex_check",
    "格式": "regex_check",
    "格式校验": "regex_check",
    "顺序": "sequence_order_check",
    "顺序校验": "sequence_order_check",
    "连续": "sequence_order_check",
    "引用": "cross_table_mapping",
    "引用存在": "cross_table_mapping",
    "包含": "cross_table_mapping",
    "包含(in)": "cross_table_mapping",
    "字典": "cross_table_mapping",
    "组合分支": "composite_condition_check",
    "组合分支校验": "composite_condition_check",
    "条件分支": "composite_condition_check",
    "跨组变量": "dual_composite_compare",
    "跨组变量校验": "dual_composite_compare",
    "按key对比": "dual_composite_compare",
    "双组合变量": "dual_composite_compare",
    "多组串行": "multi_composite_pipeline_check",
    "多组串行校验": "multi_composite_pipeline_check",
    "多节点串行": "multi_composite_pipeline_check",
    "多组映射": "multi_composite_mapping_check",
    "多组映射校验": "multi_composite_mapping_check",
    "多节点映射": "multi_composite_mapping_check",
    "IAP礼包校验": "package_items_compare",
    "IAP 礼包校验": "package_items_compare",
    "礼包校验": "package_items_compare",
    "礼包道具校验": "package_items_compare",
    "节日任务校验": "event_task_reward",
    "节日任务奖励校验": "event_task_reward",
    "EventTask校验": "event_task_reward",
    "EventTask奖励校验": "event_task_reward",
}
TEMPLATE_LABELS = (
    "数据源",
    "配置表链接",
    "配置表路径",
    "sheet分页",
    "Sheet分页",
    "sheet",
    "Sheet",
    "变量选择",
    "规则类型",
    "rule_type",
    "目标字段",
    "目标",
    "目标列名",
    "校验字段",
    "筛选条件",
    "筛选",
    "左侧筛选",
    "右侧筛选",
    "Key字段",
    "Key 字段",
    "Key值选择",
    "Key选择",
    "Key值",
    "选择Key",
    "Key",
    "关联Key",
    "引用对象",
    "比较字段",
    "筛选规则1",
    "筛选规则2",
    "校验规则",
    "最终判定",
    "校验判定",
    "判定",
    "断言",
    "规则参数",
    "规则是",
    "补充说明",
)
TEMPLATE_PLACEHOLDERS = {
    "配置表链接",
    "sheet名",
    "变量1,变量2",
    "目标字段",
    "从 not_null / unique / fixed_value_compare / regex_check / sequence_order_check / cross_table_mapping / composite_condition_check / dual_composite_compare / multi_composite_pipeline_check / multi_composite_mapping_check / package_items_compare 中选择",
    "字段或内容",
    "全部数据 / 满足 xxx 的数据",
    "字段名",
    "不能为空 / 不能重复 / 只能是 A,B,C / 必须等于字段 X / 必须存在于引用表 / 匹配正则 xxx",
    "可选，比如排序方向、正则、引用表、比较字段",
}
