import type { ComputedRef, Ref } from 'vue'

import {
  COMPOSITE_ASSERTION_OPTIONS,
  COMPOSITE_COMPARE_OPERATORS,
  COMPOSITE_FILTER_OPTIONS,
  COMPARE_RULE_SELECTIONS,
  DUAL_COMPOSITE_OPERATOR_OPTIONS,
  EXPECTED_VALUE_MODE_OPTIONS,
  KEY_FIELD,
  OPERATOR_SYMBOL_MAP,
  PIPELINE_ASSERTION_OPTIONS,
  RULE_ENTRY_TYPE_OPTIONS,
  RULE_SELECTION_NAME_MAP,
  RULE_SELECTION_OPTIONS,
  applyConditionCompareValueKind,
  getConditionCompareValueKind as getSharedConditionCompareValueKind,
  getConditionCompareValueKindOptions as getSharedConditionCompareValueKindOptions,
  shouldShowConditionCompareValueKind as shouldShowSharedConditionCompareValueKind,
  type ConditionCompareValueKind,
} from '../../rules'
import type {
  CompositeAssertionOperator,
  CompositeBranch,
  CompositeCondition,
  CompositeFilterOperator,
  CompositeRuleConfig,
  DualCompositeComparison,
  ExpectedValueMode,
  FixedRuleDefinition,
  FixedRuleSelection,
  MultiCompositeMappingConfig,
  MultiCompositeMappingExclusionRange,
  MultiCompositeMappingFilter,
  MultiCompositeMappingNode,
  MultiCompositePipelineConfig,
  MultiCompositePipelineNode,
  PipelineAssertionOperator,
} from '../../types/fixedRules'
import type { DataSource, VariableTag } from '../../types/workbench'
import type { RuleFormState } from './types'
import {
  buildCompositeFieldOptions,
  buildDefaultRuleName as buildSharedDefaultRuleName,
  buildDisplayFieldOptions,
  buildSequenceSummary,
  createBranch as createSharedBranch,
  createCondition as createSharedCondition,
  createDualCompositeComparison as createSharedDualCompositeComparison,
  createId,
  createMappingExclusionRange as createSharedMappingExclusionRange,
  createMappingFilter as createSharedMappingFilter,
  createMappingNode as createSharedMappingNode,
  createPipelineNode as createSharedPipelineNode,
  getCompositeFieldLabel as getSharedCompositeFieldLabel,
  getDualCompositeKeyCheckModeLabel,
  getDualCompositeOperatorLabel,
  getExpectedValueModeHelpText,
  getOperatorLabel,
  getRuleEntryTypeBySelection,
  getRuleSelectionLabel,
  getRuleSelectionName,
  getRuleSelectionValue,
  getSequenceDirectionLabel,
  getSourcePath,
  getVariableColumnSummary,
  isCompareRuleSelection,
  isCompositeCompareOperator,
  isCompositeContainsOperator,
  isCompositeRegexOperator,
  normalizeCompositeConfig as normalizeSharedCompositeConfig,
  normalizeDisplayField,
  normalizeExpectedValueMode,
  normalizeMappingConfig as normalizeSharedMappingConfig,
  normalizePipelineConfig as normalizeSharedPipelineConfig,
  parseExpectedValueSet,
  resolveFieldOptionValue,
  shouldShowConditionExpectedValueMode,
  summarizeCondition,
  type ConditionMode,
  type FieldOption,
} from './utils/workbenchRuleForm'

interface RuleOrchestrationEditingOptions {
  dualComparisonIdPrefix?: string
  normalizeDualComparisonFields?: boolean
}

interface UseRuleOrchestrationEditingInput {
  ruleForm: RuleFormState
  compositeRuleForm: CompositeRuleConfig
  dualCompositeComparisons: Ref<DualCompositeComparison[]>
  dualCompositeLeftFilters: Ref<CompositeCondition[]>
  dualCompositeRightFilters: Ref<CompositeCondition[]>
  pipelineRuleForm: MultiCompositePipelineConfig
  mappingRuleForm: MultiCompositeMappingConfig
  compositeVariableOptions: ComputedRef<VariableTag[]>
  variableMap: ComputedRef<Map<string, VariableTag>>
  sourceMap: ComputedRef<Map<string, DataSource>>
  selectedRuleVariable: ComputedRef<VariableTag | null>
  compositeFieldOptions: ComputedRef<FieldOption[]>
  referenceCompositeFieldOptions: ComputedRef<FieldOption[]>
  isMultiCompositePipelineRule: ComputedRef<boolean>
  isMultiCompositeMappingRule: ComputedRef<boolean>
  isInitializingRuleDialog: Ref<boolean>
  isApplyingSystemRuleName: Ref<boolean>
  isRuleNameManuallyEdited: Ref<boolean>
  lastAutoGeneratedRuleName: Ref<string>
  options?: RuleOrchestrationEditingOptions
}

export function useRuleOrchestrationEditing(input: UseRuleOrchestrationEditingInput) {
  const {
    ruleForm,
    compositeRuleForm,
    dualCompositeComparisons,
    dualCompositeLeftFilters,
    dualCompositeRightFilters,
    pipelineRuleForm,
    mappingRuleForm,
    compositeVariableOptions,
    variableMap,
    sourceMap,
    selectedRuleVariable,
    compositeFieldOptions,
    referenceCompositeFieldOptions,
    isMultiCompositePipelineRule,
    isMultiCompositeMappingRule,
    isInitializingRuleDialog,
    isApplyingSystemRuleName,
    isRuleNameManuallyEdited,
    lastAutoGeneratedRuleName,
  } = input
  const dualComparisonIdPrefix = input.options?.dualComparisonIdPrefix ?? 'comparison'
  const normalizeDualComparisonFields = input.options?.normalizeDualComparisonFields ?? true

  function setRuleFormExpectedValueMode(value: string): void {
    ruleForm.expected_value_mode = normalizeExpectedValueMode(value as ExpectedValueMode)
  }

  function createCondition(): CompositeCondition {
    return createSharedCondition()
  }

  function createBranch(): CompositeBranch {
    return createSharedBranch()
  }

  function createDualCompositeComparison(): DualCompositeComparison {
    return createSharedDualCompositeComparison()
  }

  function getDefaultCompositeVariableTag(preferred = ''): string {
    const normalizedPreferred = preferred.trim()
    if (
      normalizedPreferred &&
      compositeVariableOptions.value.some((variable) => variable.tag === normalizedPreferred)
    ) {
      return normalizedPreferred
    }
    return compositeVariableOptions.value[0]?.tag ?? ''
  }

  function createPipelineNode(preferredVariableTag = ''): MultiCompositePipelineNode {
    return createSharedPipelineNode(compositeVariableOptions.value, preferredVariableTag)
  }

  function createMappingExclusionRange(startRow = 2): MultiCompositeMappingExclusionRange {
    return createSharedMappingExclusionRange(startRow)
  }

  function createMappingFilter(): MultiCompositeMappingFilter {
    return createSharedMappingFilter()
  }

  function createMappingNode(preferredVariableTag = ''): MultiCompositeMappingNode {
    return createSharedMappingNode(compositeVariableOptions.value, preferredVariableTag)
  }

  function normalizeCompositeConfig(config?: CompositeRuleConfig): CompositeRuleConfig {
    return normalizeSharedCompositeConfig(config)
  }

  function applyCompositeConfig(config?: CompositeRuleConfig): void {
    const next = normalizeCompositeConfig(config)
    compositeRuleForm.global_filters = next.global_filters
    compositeRuleForm.branches = next.branches
  }

  function resetCompositeConfig(): void {
    applyCompositeConfig(undefined)
  }

  function normalizeDualCompositeComparisons(
    comparisons?: DualCompositeComparison[],
  ): DualCompositeComparison[] {
    const nextComparisons = (
      comparisons?.length ? comparisons : [createDualCompositeComparison()]
    ).map((comparison) => {
      if (!normalizeDualComparisonFields) {
        return {
          ...comparison,
          comparison_id: comparison.comparison_id || createId(dualComparisonIdPrefix),
        }
      }
      return {
        comparison_id: comparison.comparison_id || createId(dualComparisonIdPrefix),
        left_field: comparison.left_field?.trim() ?? '',
        operator: comparison.operator ?? 'eq',
        right_field: comparison.right_field?.trim() ?? '',
      }
    })
    return nextComparisons.length ? nextComparisons : [createDualCompositeComparison()]
  }

  function normalizeDualCompositeFilters(filters?: CompositeCondition[]): CompositeCondition[] {
    return (filters ?? []).map((condition) => ({
      ...condition,
      condition_id: condition.condition_id || createId('condition'),
    }))
  }

  function applyDualCompositeComparisons(comparisons?: DualCompositeComparison[]): void {
    dualCompositeComparisons.value = normalizeDualCompositeComparisons(comparisons)
  }

  function resetDualCompositeComparisons(): void {
    applyDualCompositeComparisons(undefined)
  }

  function applyDualCompositeFilters(
    leftFilters?: CompositeCondition[],
    rightFilters?: CompositeCondition[],
  ): void {
    dualCompositeLeftFilters.value = normalizeDualCompositeFilters(leftFilters)
    dualCompositeRightFilters.value = normalizeDualCompositeFilters(rightFilters)
  }

  function resetDualCompositeFilters(): void {
    applyDualCompositeFilters()
  }

  function resetDualCompositeKeyFields(): void {
    ruleForm.left_key_field = KEY_FIELD
    ruleForm.right_key_field = KEY_FIELD
  }

  function normalizePipelineConfig(
    config?: MultiCompositePipelineConfig,
    preferredVariableTag = '',
  ): MultiCompositePipelineConfig {
    return normalizeSharedPipelineConfig(config, compositeVariableOptions.value, preferredVariableTag)
  }

  function applyPipelineConfig(
    config?: MultiCompositePipelineConfig,
    preferredVariableTag = '',
  ): void {
    const next = normalizePipelineConfig(config, preferredVariableTag)
    pipelineRuleForm.nodes = next.nodes
  }

  function resetPipelineConfig(preferredVariableTag = ''): void {
    applyPipelineConfig(undefined, preferredVariableTag)
  }

  function normalizeMappingConfig(
    config?: MultiCompositeMappingConfig,
    preferredVariableTag = '',
  ): MultiCompositeMappingConfig {
    return normalizeSharedMappingConfig(config, compositeVariableOptions.value, preferredVariableTag)
  }

  function applyMappingConfig(
    config?: MultiCompositeMappingConfig,
    preferredVariableTag = '',
  ): void {
    const next = normalizeMappingConfig(config, preferredVariableTag)
    mappingRuleForm.nodes = next.nodes
  }

  function resetMappingConfig(preferredVariableTag = ''): void {
    applyMappingConfig(undefined, preferredVariableTag)
  }

  function getNodeDisplayFieldOptions(
    node: MultiCompositePipelineNode | MultiCompositeMappingNode,
  ): FieldOption[] {
    return buildDisplayFieldOptions(variableMap.value.get(node.variable_tag) ?? null)
  }

  function addPipelineNode(): void {
    pipelineRuleForm.nodes.push(createPipelineNode())
  }

  function removePipelineNode(nodeId: string): void {
    pipelineRuleForm.nodes = pipelineRuleForm.nodes.filter((node) => node.node_id !== nodeId)
  }

  function movePipelineNode(nodeId: string, direction: 'up' | 'down'): void {
    const currentIndex = pipelineRuleForm.nodes.findIndex((node) => node.node_id === nodeId)
    if (currentIndex < 0) {
      return
    }
    const targetIndex = direction === 'up' ? currentIndex - 1 : currentIndex + 1
    if (targetIndex < 0 || targetIndex >= pipelineRuleForm.nodes.length) {
      return
    }
    const nextNodes = [...pipelineRuleForm.nodes]
    const [currentNode] = nextNodes.splice(currentIndex, 1)
    nextNodes.splice(targetIndex, 0, currentNode)
    pipelineRuleForm.nodes = nextNodes
  }

  function addPipelineNodeFilter(node: MultiCompositePipelineNode): void {
    node.filters.push(createCondition())
  }

  function removePipelineNodeFilter(
    node: MultiCompositePipelineNode,
    conditionId: string,
  ): void {
    node.filters = node.filters.filter((condition) => condition.condition_id !== conditionId)
  }

  function addPipelineNodeAssertion(node: MultiCompositePipelineNode): void {
    node.assertions.push(createCondition())
  }

  function removePipelineNodeAssertion(
    node: MultiCompositePipelineNode,
    conditionId: string,
  ): void {
    node.assertions = node.assertions.filter((condition) => condition.condition_id !== conditionId)
  }

  function getPipelineNodeVariable(node: MultiCompositePipelineNode): VariableTag | null {
    return variableMap.value.get(node.variable_tag) ?? null
  }

  function getPipelineNodeFieldOptions(node: MultiCompositePipelineNode): FieldOption[] {
    return buildCompositeFieldOptions(getPipelineNodeVariable(node))
  }

  function handlePipelineNodeVariableChange(nodeIndex: number, value: string): void {
    const node = pipelineRuleForm.nodes[nodeIndex]
    if (!node) {
      return
    }
    node.variable_tag = value
    node.display_field = normalizeDisplayField(
      node.display_field ?? '',
      getNodeDisplayFieldOptions(node),
    )
  }

  function addMappingNode(): void {
    mappingRuleForm.nodes.push(createMappingNode())
  }

  function removeMappingNode(nodeId: string): void {
    mappingRuleForm.nodes = mappingRuleForm.nodes.filter((node) => node.node_id !== nodeId)
  }

  function moveMappingNode(nodeId: string, direction: 'up' | 'down'): void {
    const currentIndex = mappingRuleForm.nodes.findIndex((node) => node.node_id === nodeId)
    if (currentIndex < 0) {
      return
    }
    const targetIndex = direction === 'up' ? currentIndex - 1 : currentIndex + 1
    if (targetIndex < 0 || targetIndex >= mappingRuleForm.nodes.length) {
      return
    }
    const nextNodes = [...mappingRuleForm.nodes]
    const [currentNode] = nextNodes.splice(currentIndex, 1)
    nextNodes.splice(targetIndex, 0, currentNode)
    mappingRuleForm.nodes = nextNodes
  }

  function addMappingNodeFilter(node: MultiCompositeMappingNode): void {
    node.filters.push(createMappingFilter())
  }

  function removeMappingNodeFilter(node: MultiCompositeMappingNode, conditionId: string): void {
    node.filters = node.filters.filter((condition) => condition.condition_id !== conditionId)
  }

  function getMappingNodeVariable(node: MultiCompositeMappingNode): VariableTag | null {
    return variableMap.value.get(node.variable_tag) ?? null
  }

  function getMappingNodeFieldOptions(node: MultiCompositeMappingNode): FieldOption[] {
    return buildCompositeFieldOptions(getMappingNodeVariable(node))
  }

  function handleMappingNodeVariableChange(nodeIndex: number, value: string): void {
    const node = mappingRuleForm.nodes[nodeIndex]
    if (!node) {
      return
    }
    node.variable_tag = value
    node.display_field = normalizeDisplayField(
      node.display_field ?? '',
      getNodeDisplayFieldOptions(node),
    )
    node.filters = []
  }

  function getNextMappingExclusionRangeStart(condition: MultiCompositeMappingFilter): number {
    if (!condition.exclusion_ranges.length) {
      return 2
    }
    const lastEnd = Math.max(
      ...condition.exclusion_ranges.map((range) => Number(range.end_row) || 1),
    )
    return lastEnd + 1
  }

  function addMappingExclusionRange(condition: MultiCompositeMappingFilter): void {
    condition.exclusion_ranges.push(
      createMappingExclusionRange(getNextMappingExclusionRangeStart(condition)),
    )
  }

  function removeMappingExclusionRange(
    condition: MultiCompositeMappingFilter,
    rangeId: string,
  ): void {
    condition.exclusion_ranges = condition.exclusion_ranges.filter(
      (range) => range.range_id !== rangeId,
    )
  }

  function addGlobalFilter(): void {
    compositeRuleForm.global_filters.push(createCondition())
  }

  function removeGlobalFilter(conditionId: string): void {
    compositeRuleForm.global_filters = compositeRuleForm.global_filters.filter(
      (condition) => condition.condition_id !== conditionId,
    )
  }

  function addBranch(): void {
    compositeRuleForm.branches.push(createBranch())
  }

  function removeBranch(branchId: string): void {
    compositeRuleForm.branches = compositeRuleForm.branches.filter(
      (branch) => branch.branch_id !== branchId,
    )
  }

  function addBranchFilter(branch: CompositeBranch): void {
    branch.filters.push(createCondition())
  }

  function removeBranchFilter(branch: CompositeBranch, conditionId: string): void {
    branch.filters = branch.filters.filter((condition) => condition.condition_id !== conditionId)
  }

  function addBranchAssertion(branch: CompositeBranch): void {
    branch.assertions.push(createCondition())
  }

  function removeBranchAssertion(branch: CompositeBranch, conditionId: string): void {
    branch.assertions = branch.assertions.filter(
      (condition) => condition.condition_id !== conditionId,
    )
  }

  function addDualCompositeComparison(): void {
    dualCompositeComparisons.value.push(createDualCompositeComparison())
  }

  function removeDualCompositeComparison(comparisonId: string): void {
    dualCompositeComparisons.value = dualCompositeComparisons.value.filter(
      (comparison) => comparison.comparison_id !== comparisonId,
    )
  }

  function addDualCompositeFilter(side: 'left' | 'right'): void {
    if (side === 'left') {
      dualCompositeLeftFilters.value.push(createCondition())
      return
    }
    dualCompositeRightFilters.value.push(createCondition())
  }

  function removeDualCompositeFilter(side: 'left' | 'right', conditionId: string): void {
    if (side === 'left') {
      dualCompositeLeftFilters.value = dualCompositeLeftFilters.value.filter(
        (condition) => condition.condition_id !== conditionId,
      )
      return
    }
    dualCompositeRightFilters.value = dualCompositeRightFilters.value.filter(
      (condition) => condition.condition_id !== conditionId,
    )
  }

  function setConditionOperator(
    condition: CompositeCondition,
    operator: CompositeFilterOperator | CompositeAssertionOperator,
  ): void {
    condition.operator = operator
    if (isCompositeContainsOperator(operator)) {
      condition.value_source = 'literal'
      condition.expected_field = undefined
      condition.expected_value_mode = undefined
      if (typeof condition.expected_value !== 'string') {
        condition.expected_value = ''
      }
      return
    }
    if (isCompositeRegexOperator(operator)) {
      condition.value_source = undefined
      condition.expected_field = undefined
      condition.expected_value_mode = undefined
      if (typeof condition.expected_value !== 'string') {
        condition.expected_value = ''
      }
      return
    }
    if (!isCompositeCompareOperator(operator)) {
      condition.value_source = undefined
      condition.expected_value = undefined
      condition.expected_value_mode = undefined
      condition.expected_field = undefined
      return
    }

    if (condition.value_source !== 'field' && condition.value_source !== 'literal') {
      condition.value_source = 'literal'
    }
    if (condition.value_source === 'field') {
      condition.expected_value = undefined
      condition.expected_value_mode = undefined
    } else {
      condition.expected_field = undefined
      condition.expected_value_mode =
        operator === 'eq' || operator === 'ne'
          ? normalizeExpectedValueMode(condition.expected_value_mode)
          : undefined
    }
  }

  function shouldShowConditionCompareValueKind(condition: CompositeCondition): boolean {
    return shouldShowSharedConditionCompareValueKind(condition)
  }

  function getConditionCompareValueKind(condition: CompositeCondition): ConditionCompareValueKind {
    return getSharedConditionCompareValueKind(condition)
  }

  function getConditionCompareValueKindOptions(condition: CompositeCondition) {
    return getSharedConditionCompareValueKindOptions(condition)
  }

  function setConditionCompareValueKind(condition: CompositeCondition, value: string): void {
    applyConditionCompareValueKind(condition, value as ConditionCompareValueKind)
  }

  function shouldShowConditionExpectedValue(condition: CompositeCondition): boolean {
    if (isCompositeContainsOperator(condition.operator) || isCompositeRegexOperator(condition.operator)) {
      return true
    }
    return (
      isCompositeCompareOperator(condition.operator) &&
      (condition.value_source ?? 'literal') === 'literal'
    )
  }

  function shouldShowConditionExpectedField(condition: CompositeCondition): boolean {
    return isCompositeCompareOperator(condition.operator) && condition.value_source === 'field'
  }

  function getConditionExpectedValuePlaceholder(condition: CompositeCondition): string {
    if (isCompositeContainsOperator(condition.operator)) {
      return condition.operator === 'not_contains' ? '输入要排除的片段' : '输入要匹配的片段'
    }
    if (isCompositeRegexOperator(condition.operator)) {
      return '输入完整正则表达式'
    }
    if (shouldShowConditionExpectedValueMode(condition) && condition.expected_value_mode === 'set') {
      return '例如：0,1,2'
    }
    return '输入比较值'
  }

  function getConditionOptions(mode: ConditionMode) {
    return mode === 'filter' ? COMPOSITE_FILTER_OPTIONS : COMPOSITE_ASSERTION_OPTIONS
  }

  function getPipelineConditionOptions(mode: ConditionMode) {
    return mode === 'filter' ? COMPOSITE_FILTER_OPTIONS : PIPELINE_ASSERTION_OPTIONS
  }

  function handleFilterOperatorChange(condition: CompositeCondition, value: string): void {
    setConditionOperator(condition, value as CompositeFilterOperator)
  }

  function handleAssertionOperatorChange(condition: CompositeCondition, value: string): void {
    setConditionOperator(condition, value as CompositeAssertionOperator)
  }

  function handlePipelineAssertionOperatorChange(
    condition: CompositeCondition,
    value: string,
  ): void {
    setConditionOperator(condition, value as PipelineAssertionOperator)
  }

  function isKnownCompositeField(field: string, options = compositeFieldOptions.value): boolean {
    return resolveFieldOptionValue(options, field) !== null
  }

  function validateCompositeCondition(
    condition: CompositeCondition,
    mode: ConditionMode,
    label: string,
    options = compositeFieldOptions.value,
    allowSetAssertions = true,
  ): string | null {
    if (!condition.field.trim()) {
      return `${label}缺少字段。`
    }
    if (!isKnownCompositeField(condition.field, options)) {
      return `${label}引用了当前组合变量中不存在的字段。`
    }
    if (
      mode === 'filter' &&
      (condition.operator === 'unique' || condition.operator === 'duplicate_required')
    ) {
      return `${label}的筛选条件不支持唯一或必须重复。`
    }
    if (
      mode === 'assertion' &&
      !allowSetAssertions &&
      (condition.operator === 'unique' || condition.operator === 'duplicate_required')
    ) {
      return `${label}不支持唯一或必须重复。`
    }
    if (isCompositeContainsOperator(condition.operator)) {
      if (condition.value_source === 'field') {
        return `${label}的${condition.operator === 'not_contains' ? '不包含' : '包含'}条件只支持固定值。`
      }
      if (!condition.expected_value?.trim()) {
        return `${label}缺少比较值。`
      }
      return null
    }
    if (isCompositeRegexOperator(condition.operator)) {
      if (mode !== 'assertion') {
        return `${label}的正则校验只能用于分支校验条件。`
      }
      if (!condition.expected_value?.trim()) {
        return `${label}缺少正则表达式。`
      }
      return null
    }
    if (!isCompositeCompareOperator(condition.operator)) {
      return null
    }

    if ((condition.value_source ?? 'literal') === 'field') {
      if (!condition.expected_field?.trim()) {
        return `${label}缺少右侧字段。`
      }
      if (!isKnownCompositeField(condition.expected_field, options)) {
        return `${label}引用了无效的右侧字段。`
      }
      return null
    }

    if (!condition.expected_value?.trim()) {
      return `${label}缺少比较值。`
    }
    if (
      shouldShowConditionExpectedValueMode(condition) &&
      condition.expected_value_mode === 'set' &&
      parseExpectedValueSet(condition.expected_value).length === 0
    ) {
      return `${label}的规则集至少需要一个固定值。`
    }
    if (
      (condition.operator === 'gt' || condition.operator === 'lt') &&
      Number.isNaN(Number(condition.expected_value))
    ) {
      return `${label}的大于/小于比较值必须是合法数字。`
    }
    return null
  }

  function isKnownReferenceCompositeField(field: string): boolean {
    return isKnownCompositeField(field, referenceCompositeFieldOptions.value)
  }

  function validateDualCompositeKeyField(
    field: string,
    sideLabel: string,
    options: FieldOption[],
  ): string | null {
    if (!field.trim()) {
      return `${sideLabel}关联 Key 字段不能为空。`
    }
    if (resolveFieldOptionValue(options, field) === null) {
      return `${sideLabel}关联 Key 字段不属于对应组合变量。`
    }
    return null
  }

  function validateDualCompositeFilters(
    filters: CompositeCondition[],
    sideLabel: string,
    options: FieldOption[],
  ): string | null {
    for (let index = 0; index < filters.length; index += 1) {
      const error = validateCompositeCondition(
        filters[index],
        'filter',
        `${sideLabel}筛选条件 ${index + 1}`,
        options,
      )
      if (error) {
        return error
      }
    }
    return null
  }

  function validateDualCompositeComparison(
    comparison: DualCompositeComparison,
    label: string,
  ): string | null {
    if (!comparison.left_field.trim()) {
      return `${label}缺少变量 1 字段。`
    }
    if (!isKnownCompositeField(comparison.left_field)) {
      return `${label}引用了基准变量中不存在的字段。`
    }
    if (!comparison.right_field.trim()) {
      return `${label}缺少变量 2 字段。`
    }
    if (!isKnownReferenceCompositeField(comparison.right_field)) {
      return `${label}引用了目标变量中不存在的字段。`
    }
    if (
      (comparison.operator === 'gt' || comparison.operator === 'lt') &&
      comparison.left_field === KEY_FIELD
    ) {
      return `${label}暂不支持使用 Key 做大小比较。`
    }
    return null
  }

  function getMappingRangeStartError(range: MultiCompositeMappingExclusionRange): string {
    if (range.start_row == null) {
      return '请输入起始行号'
    }
    const startRow = Number(range.start_row)
    if (!Number.isInteger(startRow) || startRow <= 0) {
      return '行号必须为正整数'
    }
    const endRow = Number(range.end_row)
    if (Number.isInteger(endRow) && endRow > 0 && startRow > endRow) {
      return '起始行号不能大于结束行号'
    }
    return ''
  }

  function getMappingRangeEndError(range: MultiCompositeMappingExclusionRange): string {
    if (range.end_row == null) {
      return '请输入结束行号'
    }
    const endRow = Number(range.end_row)
    if (!Number.isInteger(endRow) || endRow <= 0) {
      return '行号必须为正整数'
    }
    const startRow = Number(range.start_row)
    if (Number.isInteger(startRow) && startRow > 0 && startRow > endRow) {
      return '起始行号不能大于结束行号'
    }
    return ''
  }

  function getMappingRangeExpectedValueError(range: MultiCompositeMappingExclusionRange): string {
    const expectedValues = (range.expected_value ?? '')
      .split(',')
      .map((value) => value.trim())
      .filter(Boolean)
    return expectedValues.length ? '' : '请输入判定值，多个值用英文逗号分隔'
  }

  function validateMappingExclusionRanges(
    ranges: MultiCompositeMappingExclusionRange[],
    label: string,
  ): string | null {
    for (let index = 0; index < ranges.length; index += 1) {
      const range = ranges[index]
      const startError = getMappingRangeStartError(range)
      if (startError) {
        return `${label}第 ${index + 1} 段排除范围：${startError}。`
      }
      const endError = getMappingRangeEndError(range)
      if (endError) {
        return `${label}第 ${index + 1} 段排除范围：${endError}。`
      }
      const expectedValueError = getMappingRangeExpectedValueError(range)
      if (expectedValueError) {
        return `${label}第 ${index + 1} 段排除范围：${expectedValueError}。`
      }
    }
    return null
  }

  function getCompositeFieldLabel(field: string, variable: VariableTag | null): string {
    return getSharedCompositeFieldLabel(field, variable)
  }

  function resolveRuleVariable(rule: FixedRuleDefinition): VariableTag | null {
    return variableMap.value.get(rule.target_variable_tag) ?? null
  }

  function resolveRuleSource(rule: FixedRuleDefinition): DataSource | null {
    const variable = resolveRuleVariable(rule)
    return variable ? sourceMap.value.get(variable.source_id) ?? null : null
  }

  function buildVariableOptionLabel(variable: VariableTag): string {
    return variable.tag
  }

  function buildDefaultRuleName(
    variable: VariableTag | null,
    selectedRule: FixedRuleSelection,
    expectedValue: string,
    referenceVariableTag = '',
  ): string {
    return buildSharedDefaultRuleName({
      variable,
      selectedRule,
      expectedValue,
      referenceVariableTag,
      variableMap: variableMap.value,
      dualCompositeComparisons: dualCompositeComparisons.value,
    })
  }

  function buildDefaultRuleNameFromForm(): string {
    const nodeVariable = isMultiCompositePipelineRule.value
      ? variableMap.value.get(pipelineRuleForm.nodes[0]?.variable_tag ?? '') ?? null
      : isMultiCompositeMappingRule.value
        ? variableMap.value.get(mappingRuleForm.nodes[0]?.variable_tag ?? '') ?? null
        : selectedRuleVariable.value
    return buildDefaultRuleName(
      nodeVariable,
      ruleForm.selected_rule,
      ruleForm.expected_value,
      ruleForm.reference_variable_tag,
    )
  }

  function applySystemRuleName(nextRuleName: string): void {
    isApplyingSystemRuleName.value = true
    ruleForm.rule_name = nextRuleName
    lastAutoGeneratedRuleName.value = nextRuleName
    isRuleNameManuallyEdited.value = false
    isApplyingSystemRuleName.value = false
  }

  function syncRuleNameWithForm(): void {
    if (isInitializingRuleDialog.value || isRuleNameManuallyEdited.value) {
      return
    }

    const nextRuleName = buildDefaultRuleNameFromForm()
    const currentRuleName = ruleForm.rule_name.trim()
    if (!nextRuleName) {
      if (!currentRuleName || currentRuleName === lastAutoGeneratedRuleName.value) {
        applySystemRuleName('')
      }
      return
    }

    if (currentRuleName !== nextRuleName || lastAutoGeneratedRuleName.value !== nextRuleName) {
      applySystemRuleName(nextRuleName)
    }
  }

  return {
    KEY_FIELD,
    ruleSelectionOptions: RULE_SELECTION_OPTIONS,
    ruleEntryTypeOptions: RULE_ENTRY_TYPE_OPTIONS,
    dualCompositeOperatorOptions: DUAL_COMPOSITE_OPERATOR_OPTIONS,
    compositeFilterOptions: COMPOSITE_FILTER_OPTIONS,
    compositeAssertionOptions: COMPOSITE_ASSERTION_OPTIONS,
    pipelineAssertionOptions: PIPELINE_ASSERTION_OPTIONS,
    compareRuleSelections: COMPARE_RULE_SELECTIONS,
    compositeCompareOperators: COMPOSITE_COMPARE_OPERATORS,
    ruleSelectionNameMap: RULE_SELECTION_NAME_MAP,
    operatorSymbolMap: OPERATOR_SYMBOL_MAP,
    expectedValueModeOptions: EXPECTED_VALUE_MODE_OPTIONS,
    buildCompositeFieldOptions,
    buildDisplayFieldOptions,
    resolveFieldOptionValue,
    isCompareRuleSelection,
    isCompositeCompareOperator,
    isCompositeContainsOperator,
    isCompositeRegexOperator,
    normalizeExpectedValueMode,
    parseExpectedValueSet,
    shouldShowConditionExpectedValueMode,
    setRuleFormExpectedValueMode,
    getExpectedValueModeHelpText,
    createId,
    createCondition,
    createBranch,
    createDualCompositeComparison,
    getDefaultCompositeVariableTag,
    createPipelineNode,
    createMappingExclusionRange,
    createMappingFilter,
    createMappingNode,
    normalizeCompositeConfig,
    applyCompositeConfig,
    resetCompositeConfig,
    normalizeDualCompositeComparisons,
    normalizeDualCompositeFilters,
    getRuleEntryTypeBySelection,
    applyDualCompositeComparisons,
    resetDualCompositeComparisons,
    applyDualCompositeFilters,
    resetDualCompositeFilters,
    resetDualCompositeKeyFields,
    normalizePipelineConfig,
    applyPipelineConfig,
    resetPipelineConfig,
    normalizeMappingConfig,
    applyMappingConfig,
    resetMappingConfig,
    getNodeDisplayFieldOptions,
    normalizeDisplayField,
    addPipelineNode,
    removePipelineNode,
    movePipelineNode,
    addPipelineNodeFilter,
    removePipelineNodeFilter,
    addPipelineNodeAssertion,
    removePipelineNodeAssertion,
    getPipelineNodeVariable,
    getPipelineNodeFieldOptions,
    handlePipelineNodeVariableChange,
    addMappingNode,
    removeMappingNode,
    moveMappingNode,
    addMappingNodeFilter,
    removeMappingNodeFilter,
    getMappingNodeVariable,
    getMappingNodeFieldOptions,
    handleMappingNodeVariableChange,
    getNextMappingExclusionRangeStart,
    addMappingExclusionRange,
    removeMappingExclusionRange,
    addGlobalFilter,
    removeGlobalFilter,
    addBranch,
    removeBranch,
    addBranchFilter,
    removeBranchFilter,
    addBranchAssertion,
    removeBranchAssertion,
    addDualCompositeComparison,
    removeDualCompositeComparison,
    addDualCompositeFilter,
    removeDualCompositeFilter,
    setConditionOperator,
    shouldShowConditionCompareValueKind,
    getConditionCompareValueKind,
    getConditionCompareValueKindOptions,
    setConditionCompareValueKind,
    shouldShowConditionExpectedValue,
    shouldShowConditionExpectedField,
    getConditionExpectedValuePlaceholder,
    getConditionOptions,
    getPipelineConditionOptions,
    handleFilterOperatorChange,
    handleAssertionOperatorChange,
    handlePipelineAssertionOperatorChange,
    isKnownCompositeField,
    validateCompositeCondition,
    isKnownReferenceCompositeField,
    validateDualCompositeKeyField,
    validateDualCompositeFilters,
    validateDualCompositeComparison,
    getMappingRangeStartError,
    getMappingRangeEndError,
    getMappingRangeExpectedValueError,
    validateMappingExclusionRanges,
    getDualCompositeOperatorLabel,
    getDualCompositeKeyCheckModeLabel,
    getSourcePath,
    getCompositeFieldLabel,
    resolveRuleVariable,
    resolveRuleSource,
    getOperatorLabel,
    getRuleSelectionLabel,
    getRuleSelectionName,
    getRuleSelectionValue,
    getSequenceDirectionLabel,
    buildSequenceSummary,
    getVariableColumnSummary,
    buildVariableOptionLabel,
    buildDefaultRuleName,
    buildDefaultRuleNameFromForm,
    applySystemRuleName,
    syncRuleNameWithForm,
    summarizeCondition,
  }
}
